(*
    <vscr - Verilog converter to abc format.>
    Copyright (C) <2011,2012>  <Jonathan Richard Robert Kimmitt>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*)

open VhdlTree
let asctoken = function
  | VhdAbsFactor -> "VhdAbsFactor"
  | VhdAccessTypeDefinition -> "VhdAccessTypeDefinition"
  | VhdActualDiscreteRange -> "VhdActualDiscreteRange"
  | VhdActualExpression -> "VhdActualExpression"
  | VhdActualOpen -> "VhdActualOpen"
  | VhdAddSimpleExpression -> "VhdAddSimpleExpression"
  | VhdAggregatePrimary -> "VhdAggregatePrimary"
  | VhdAlwaysLoop -> "VhdAlwaysLoop"
  | VhdAndFactor -> "VhdAndFactor"
  | VhdAndLogicalExpression -> "VhdAndLogicalExpression"
  | VhdArchitectureBody -> "VhdArchitectureBody"
  | VhdArrayConstraint -> "VhdArrayConstraint"
  | VhdArrayTypeDefinition -> "VhdArrayTypeDefinition"
  | VhdAttrNameRange -> "VhdAttrNameRange"
  | VhdAttributeName -> "VhdAttributeName"
  | VhdBindingConfiguration -> "VhdBindingConfiguration"
  | VhdBindingEntity -> "VhdBindingEntity"
  | VhdBindingEntityArchitecture -> "VhdBindingEntityArchitecture"
  | VhdBindingOpen -> "VhdBindingOpen"
  | VhdBlockAliasDeclaration -> "VhdBlockAliasDeclaration"
  | VhdBlockAttributeDeclaration -> "VhdBlockAttributeDeclaration"
  | VhdBlockAttributeSpecification -> "VhdBlockAttributeSpecification"
  | VhdBlockComponentDeclaration -> "VhdBlockComponentDeclaration"
  | VhdBlockConfiguration -> "VhdBlockConfiguration"
  | VhdBlockConfigurationSpecification -> "VhdBlockConfigurationSpecification"
  | VhdBlockConstantDeclaration -> "VhdBlockConstantDeclaration"
  | VhdBlockFileDeclaration -> "VhdBlockFileDeclaration"
  | VhdBlockSignalDeclaration -> "VhdBlockSignalDeclaration"
  | VhdBlockSpecificationEmpty -> "VhdBlockSpecificationEmpty"
  | VhdBlockSpecificationName -> "VhdBlockSpecificationName"
  | VhdBlockSpecificationNameIndex -> "VhdBlockSpecificationNameIndex"
  | VhdBlockSubProgramBody -> "VhdBlockSubProgramBody"
  | VhdBlockSubProgramDeclaration -> "VhdBlockSubProgramDeclaration"
  | VhdBlockSubProgramInstantiation -> "VhdBlockSubProgramInstantiation"
  | VhdBlockSubTypeDeclaration -> "VhdBlockSubTypeDeclaration"
  | VhdBlockTypeDeclaration -> "VhdBlockTypeDeclaration"
  | VhdBlockUseClause -> "VhdBlockUseClause"
  | VhdCaseGenerateStatement -> "VhdCaseGenerateStatement"
  | VhdCharLiteralEnumeration -> "VhdCharLiteralEnumeration"
  | VhdCharPrimary -> "VhdCharPrimary"
  | VhdChoiceDiscreteRange -> "VhdChoiceDiscreteRange"
  | VhdChoiceOthers -> "VhdChoiceOthers"
  | VhdChoiceSimpleExpression -> "VhdChoiceSimpleExpression"
  | VhdClassArchitecture -> "VhdClassArchitecture"
  | VhdClassComponent -> "VhdClassComponent"
  | VhdClassConfiguration -> "VhdClassConfiguration"
  | VhdClassConstant -> "VhdClassConstant"
  | VhdClassEntity -> "VhdClassEntity"
  | VhdClassFile -> "VhdClassFile"
  | VhdClassFunction -> "VhdClassFunction"
  | VhdClassLabel -> "VhdClassLabel"
  | VhdClassLiteral -> "VhdClassLiteral"
  | VhdClassPackage -> "VhdClassPackage"
  | VhdClassProcedure -> "VhdClassProcedure"
  | VhdClassSignal -> "VhdClassSignal"
  | VhdClassSubType -> "VhdClassSubType"
  | VhdClassType -> "VhdClassType"
  | VhdClassUnits -> "VhdClassUnits"
  | VhdClassVariable -> "VhdClassVariable"
  | VhdComponentConfiguration -> "VhdComponentConfiguration"
  | VhdConcatSimpleExpression -> "VhdConcatSimpleExpression"
  | VhdConcurrentAssertionStatement -> "VhdConcurrentAssertionStatement"
  | VhdConcurrentBlockStatement -> "VhdConcurrentBlockStatement"
  | VhdConcurrentComponentInstantiationStatement -> "VhdConcurrentComponentInstantiationStatement"
  | VhdConcurrentConditionalSignalAssignment -> "VhdConcurrentConditionalSignalAssignment"
  | VhdConcurrentGenerateStatement -> "VhdConcurrentGenerateStatement"
  | VhdConcurrentProcedureCallStatement -> "VhdConcurrentProcedureCallStatement"
  | VhdConcurrentProcessStatement -> "VhdConcurrentProcessStatement"
  | VhdConcurrentSelectedSignalAssignment -> "VhdConcurrentSelectedSignalAssignment"
  | VhdConcurrentSignalAssignmentStatement -> "VhdConcurrentSignalAssignmentStatement"
  | VhdConcurrentSimpleSignalAssignment -> "VhdConcurrentSimpleSignalAssignment"
  | VhdCondition -> "VhdCondition"
  | VhdConditionExpression -> "VhdConditionExpression"
  | VhdConditionalSignalAssignment -> "VhdConditionalSignalAssignment"
  | VhdConditionalVariableAssignment -> "VhdConditionalVariableAssignment"
  | VhdConfigurationAttributeSpecification -> "VhdConfigurationAttributeSpecification"
  | VhdConfigurationDeclaration -> "VhdConfigurationDeclaration"
  | VhdConfigurationUseClause -> "VhdConfigurationUseClause"
  | VhdConstantDeclaration -> "VhdConstantDeclaration"
  | VhdConstrainedArray -> "VhdConstrainedArray"
  | VhdContextContextReference -> "VhdContextContextReference"
  | VhdContextDeclaration -> "VhdContextDeclaration"
  | VhdContextLibraryClause -> "VhdContextLibraryClause"
  | VhdContextUseClause -> "VhdContextUseClause"
  | VhdDecreasingRange -> "VhdDecreasingRange"
  | VhdDelayInertial -> "VhdDelayInertial"
  | VhdDelayNone -> "VhdDelayNone"
  | VhdDelayTransport -> "VhdDelayTransport"
  | VhdDesignatorCharacter -> "VhdDesignatorCharacter"
  | VhdDesignatorIdentifier -> "VhdDesignatorIdentifier"
  | VhdDesignatorOperator -> "VhdDesignatorOperator"
  | VhdDivTerm -> "VhdDivTerm"
  | VhdElse -> "VhdElse"
  | VhdElseNone -> "VhdElseNone"
  | VhdElsif -> "VhdElsif"
  | VhdEntityAliasDeclaration -> "VhdEntityAliasDeclaration"
  | VhdEntityAll -> "VhdEntityAll"
  | VhdEntityAttributeDeclaration -> "VhdEntityAttributeDeclaration"
  | VhdEntityAttributeSpecification -> "VhdEntityAttributeSpecification"
  | VhdEntityConcurrentAssertionStatement -> "VhdEntityConcurrentAssertionStatement"
  | VhdEntityConcurrentProcedureCallStatement -> "VhdEntityConcurrentProcedureCallStatement"
  | VhdEntityConstantDeclaration -> "VhdEntityConstantDeclaration"
  | VhdEntityDeclaration -> "VhdEntityDeclaration"
  | VhdEntityFileDeclaration -> "VhdEntityFileDeclaration"
  | VhdEntityOthers -> "VhdEntityOthers"
  | VhdEntityProcessStatement -> "VhdEntityProcessStatement"
  | VhdEntitySignalDeclaration -> "VhdEntitySignalDeclaration"
  | VhdEntitySubProgramBody -> "VhdEntitySubProgramBody"
  | VhdEntitySubProgramDeclaration -> "VhdEntitySubProgramDeclaration"
  | VhdEntitySubProgramInstantiation -> "VhdEntitySubProgramInstantiation"
  | VhdEntitySubTypeDeclaration -> "VhdEntitySubTypeDeclaration"
  | VhdEntityTagCharacterLiteral -> "VhdEntityTagCharacterLiteral"
  | VhdEntityTagOperatorSymbol -> "VhdEntityTagOperatorSymbol"
  | VhdEntityTagSimpleName -> "VhdEntityTagSimpleName"
  | VhdEntityTypeDeclaration -> "VhdEntityTypeDeclaration"
  | VhdEntityUseClause -> "VhdEntityUseClause"
  | VhdEnumerationTypeDefinition -> "VhdEnumerationTypeDefinition"
  | VhdEqualRelation -> "VhdEqualRelation"
  | VhdExpFactor -> "VhdExpFactor"
  | VhdFileDeclaration -> "VhdFileDeclaration"
  | VhdFileTypeDefinition -> "VhdFileTypeDefinition"
  | VhdFloatPrimary -> "VhdFloatPrimary"
  | VhdForGenerateStatement -> "VhdForGenerateStatement"
  | VhdForLoop -> "VhdForLoop"
  | VhdFormalExpression -> "VhdFormalExpression"
  | VhdFormalIndexed -> "VhdFormalIndexed"
  | VhdFullType -> "VhdFullType"
  | VhdFunction -> "VhdFunction"
  | VhdFunctionSpecification -> "VhdFunctionSpecification"
  | VhdGenerateElse -> "VhdGenerateElse"
  | VhdGenerateElseNone -> "VhdGenerateElseNone"
  | VhdGenerateElsif -> "VhdGenerateElsif"
  | VhdGreaterOrEqualRelation -> "VhdGreaterOrEqualRelation"
  | VhdGreaterRelation -> "VhdGreaterRelation"
  | VhdIdentifierEnumeration -> "VhdIdentifierEnumeration"
  | VhdIfGenerateStatement -> "VhdIfGenerateStatement"
  | VhdImpure -> "VhdImpure"
  | VhdIncompleteType -> "VhdIncompleteType"
  | VhdIncreasingRange -> "VhdIncreasingRange"
  | VhdIndexDiscreteRange -> "VhdIndexDiscreteRange"
  | VhdIndexStaticExpression -> "VhdIndexStaticExpression"
  | VhdInstantiatedComponent -> "VhdInstantiatedComponent"
  | VhdInstantiatedConfiguration -> "VhdInstantiatedConfiguration"
  | VhdInstantiatedEntityArchitecture -> "VhdInstantiatedEntityArchitecture"
  | VhdInstantiationAll -> "VhdInstantiationAll"
  | VhdInstantiationOthers -> "VhdInstantiationOthers"
  | VhdIntPrimary -> "VhdIntPrimary"
  | VhdInterfaceConstantDeclaration -> "VhdInterfaceConstantDeclaration"
  | VhdInterfaceDefaultDeclaration -> "VhdInterfaceDefaultDeclaration"
  | VhdInterfaceFileDeclaration -> "VhdInterfaceFileDeclaration"
  | VhdInterfaceIncompleteTypeDeclaration -> "VhdInterfaceIncompleteTypeDeclaration"
  | VhdInterfaceModeBuffer -> "VhdInterfaceModeBuffer"
  | VhdInterfaceModeIn -> "VhdInterfaceModeIn"
  | VhdInterfaceModeInOut -> "VhdInterfaceModeInOut"
  | VhdInterfaceModeOut -> "VhdInterfaceModeOut"
  | VhdInterfaceObjectDeclaration -> "VhdInterfaceObjectDeclaration"
  | VhdInterfaceSignalDeclaration -> "VhdInterfaceSignalDeclaration"
  | VhdInterfaceTypeDeclaration -> "VhdInterfaceTypeDeclaration"
  | VhdInterfaceVariableDeclaration -> "VhdInterfaceVariableDeclaration"
  | VhdLdotted -> "VhdLdotted"
  | VhdLessOrEqualRelation -> "VhdLessOrEqualRelation"
  | VhdLessRelation -> "VhdLessRelation"
  | VhdMatchingEqualRelation -> "VhdMatchingEqualRelation"
  | VhdMatchingGreaterOrEqualRelation -> "VhdMatchingGreaterOrEqualRelation"
  | VhdMatchingGreaterRelation -> "VhdMatchingGreaterRelation"
  | VhdMatchingLessOrEqualRelation -> "VhdMatchingLessOrEqualRelation"
  | VhdMatchingLessRelation -> "VhdMatchingLessRelation"
  | VhdMatchingNotEqualRelation -> "VhdMatchingNotEqualRelation"
  | VhdMatchingSelection -> "VhdMatchingSelection"
  | VhdModTerm -> "VhdModTerm"
  | VhdMultTerm -> "VhdMultTerm"
  | VhdNameParametersPrimary -> "VhdNameParametersPrimary"
  | VhdNamePrimary -> "VhdNamePrimary"
  | VhdNandFactor -> "VhdNandFactor"
  | VhdNandLogicalExpression -> "VhdNandLogicalExpression"
  | VhdNegSimpleExpression -> "VhdNegSimpleExpression"
  | VhdNewFactor -> "VhdNewFactor"
  | VhdNoConstraint -> "VhdNoConstraint"
  | VhdNorFactor -> "VhdNorFactor"
  | VhdNorLogicalExpression -> "VhdNorLogicalExpression"
  | VhdNotEqualRelation -> "VhdNotEqualRelation"
  | VhdNotFactor -> "VhdNotFactor"
  | VhdOperatorString -> "VhdOperatorString"
  | VhdOrFactor -> "VhdOrFactor"
  | VhdOrLogicalExpression -> "VhdOrLogicalExpression"
  | VhdOrdinarySelection -> "VhdOrdinarySelection"
  | VhdPackageAliasDeclaration -> "VhdPackageAliasDeclaration"
  | VhdPackageAttributeDeclaration -> "VhdPackageAttributeDeclaration"
  | VhdPackageAttributeSpecification -> "VhdPackageAttributeSpecification"
  | VhdPackageBody -> "VhdPackageBody"
  | VhdPackageBodyAliasDeclaration -> "VhdPackageBodyAliasDeclaration"
  | VhdPackageBodyConstantDeclaration -> "VhdPackageBodyConstantDeclaration"
  | VhdPackageBodyFileDeclaration -> "VhdPackageBodyFileDeclaration"
  | VhdPackageBodySubProgramBody -> "VhdPackageBodySubProgramBody"
  | VhdPackageBodySubProgramDeclaration -> "VhdPackageBodySubProgramDeclaration"
  | VhdPackageBodySubProgramInstantiation -> "VhdPackageBodySubProgramInstantiation"
  | VhdPackageBodySubTypeDeclaration -> "VhdPackageBodySubTypeDeclaration"
  | VhdPackageBodyTypeDeclaration -> "VhdPackageBodyTypeDeclaration"
  | VhdPackageBodyUseClause -> "VhdPackageBodyUseClause"
  | VhdPackageComponentDeclaration -> "VhdPackageComponentDeclaration"
  | VhdPackageConstantDeclaration -> "VhdPackageConstantDeclaration"
  | VhdPackageDeclaration -> "VhdPackageDeclaration"
  | VhdPackageFileDeclaration -> "VhdPackageFileDeclaration"
  | VhdPackageInstantiation -> "VhdPackageInstantiation"
  | VhdPackageSignalDeclaration -> "VhdPackageSignalDeclaration"
  | VhdPackageSubProgramDeclaration -> "VhdPackageSubProgramDeclaration"
  | VhdPackageSubProgramInstantiation -> "VhdPackageSubProgramInstantiation"
  | VhdPackageSubTypeDeclaration -> "VhdPackageSubTypeDeclaration"
  | VhdPackageTypeDeclaration -> "VhdPackageTypeDeclaration"
  | VhdPackageUseClause -> "VhdPackageUseClause"
  | VhdParenthesedPrimary -> "VhdParenthesedPrimary"
  | VhdPhysicalEmpty -> "VhdPhysicalEmpty"
  | VhdPhysicalFloat -> "VhdPhysicalFloat"
  | VhdPhysicalInteger -> "VhdPhysicalInteger"
  | VhdPhysicalPrimary -> "VhdPhysicalPrimary"
  | VhdPhysicalTypeDefinition -> "VhdPhysicalTypeDefinition"
  | VhdPrefixName -> "VhdPrefixName"
  | VhdPrimaryUnit -> "VhdPrimaryUnit"
  | VhdProcedure -> "VhdProcedure"
  | VhdProcedureSpecification -> "VhdProcedureSpecification"
  | VhdProcessAliasDeclaration -> "VhdProcessAliasDeclaration"
  | VhdProcessAttributeDeclaration -> "VhdProcessAttributeDeclaration"
  | VhdProcessAttributeSpecification -> "VhdProcessAttributeSpecification"
  | VhdProcessConstantDeclaration -> "VhdProcessConstantDeclaration"
  | VhdProcessFileDeclaration -> "VhdProcessFileDeclaration"
  | VhdProcessSubProgramBody -> "VhdProcessSubProgramBody"
  | VhdProcessSubProgramDeclaration -> "VhdProcessSubProgramDeclaration"
  | VhdProcessSubProgramInstantiation -> "VhdProcessSubProgramInstantiation"
  | VhdProcessSubTypeDeclaration -> "VhdProcessSubTypeDeclaration"
  | VhdProcessTypeDeclaration -> "VhdProcessTypeDeclaration"
  | VhdProcessUseClause -> "VhdProcessUseClause"
  | VhdProcessVariableDeclaration -> "VhdProcessVariableDeclaration"
  | VhdPure -> "VhdPure"
  | VhdQualifiedAggregate -> "VhdQualifiedAggregate"
  | VhdQualifiedExpression -> "VhdQualifiedExpression"
  | VhdQualifiedExpressionPrimary -> "VhdQualifiedExpressionPrimary"
  | VhdRange -> "VhdRange"
  | VhdRangeConstraint -> "VhdRangeConstraint"
  | VhdRangeTypeDefinition -> "VhdRangeTypeDefinition"
  | VhdRecordTypeDefinition -> "VhdRecordTypeDefinition"
  | VhdRemTerm -> "VhdRemTerm"
  | VhdRotateLeftExpression -> "VhdRotateLeftExpression"
  | VhdRotateRightExpression -> "VhdRotateRightExpression"
  | VhdSecondaryUnit -> "VhdSecondaryUnit"
  | VhdSelectTargetName -> "VhdSelectTargetName"
  | VhdSelectTargetNameParameters -> "VhdSelectTargetNameParameters"
  | VhdSelectedName -> "VhdSelectedName"
  | VhdSelectedSignalAssignment -> "VhdSelectedSignalAssignment"
  | VhdSelectedVariableAssignment -> "VhdSelectedVariableAssignment"
  | VhdSelector -> "VhdSelector"
  | VhdSensitivityAll -> "VhdSensitivityAll"
  | VhdSensitivityExpressionList -> "VhdSensitivityExpressionList"
  | VhdSequentialAssertion -> "VhdSequentialAssertion"
  | VhdSequentialCase -> "VhdSequentialCase"
  | VhdSequentialExit -> "VhdSequentialExit"
  | VhdSequentialIf -> "VhdSequentialIf"
  | VhdSequentialLoop -> "VhdSequentialLoop"
  | VhdSequentialNext -> "VhdSequentialNext"
  | VhdSequentialNull -> "VhdSequentialNull"
  | VhdSequentialProcedureCall -> "VhdSequentialProcedureCall"
  | VhdSequentialReport -> "VhdSequentialReport"
  | VhdSequentialReturn -> "VhdSequentialReturn"
  | VhdSequentialSignalAssignment -> "VhdSequentialSignalAssignment"
  | VhdSequentialVariableAssignment -> "VhdSequentialVariableAssignment"
  | VhdSequentialWait -> "VhdSequentialWait"
  | VhdShiftLeftArithmeticExpression -> "VhdShiftLeftArithmeticExpression"
  | VhdShiftLeftLogicalExpression -> "VhdShiftLeftLogicalExpression"
  | VhdShiftRightArithmeticExpression -> "VhdShiftRightArithmeticExpression"
  | VhdShiftRightLogicalExpression -> "VhdShiftRightLogicalExpression"
  | VhdSignalDeclaration -> "VhdSignalDeclaration"
  | VhdSignalKindBus -> "VhdSignalKindBus"
  | VhdSignalKindDefault -> "VhdSignalKindDefault"
  | VhdSignalKindRegister -> "VhdSignalKindRegister"
  | VhdSimpleName -> "VhdSimpleName"
  | VhdSimpleSignalAssignment -> "VhdSimpleSignalAssignment"
  | VhdSimpleVariableAssignment -> "VhdSimpleVariableAssignment"
  | VhdSubProgramAliasDeclaration -> "VhdSubProgramAliasDeclaration"
  | VhdSubProgramAttributeDeclaration -> "VhdSubProgramAttributeDeclaration"
  | VhdSubProgramAttributeSpecification -> "VhdSubProgramAttributeSpecification"
  | VhdSubProgramBody -> "VhdSubProgramBody"
  | VhdSubProgramConstantDeclaration -> "VhdSubProgramConstantDeclaration"
  | VhdSubProgramDeclaration -> "VhdSubProgramDeclaration"
  | VhdSubProgramFileDeclaration -> "VhdSubProgramFileDeclaration"
  | VhdSubProgramInstantiation -> "VhdSubProgramInstantiation"
  | VhdSubProgramSubTypeDeclaration -> "VhdSubProgramSubTypeDeclaration"
  | VhdSubProgramTypeDeclaration -> "VhdSubProgramTypeDeclaration"
  | VhdSubProgramUseClause -> "VhdSubProgramUseClause"
  | VhdSubProgramVariableDeclaration -> "VhdSubProgramVariableDeclaration"
  | VhdSubSimpleExpression -> "VhdSubSimpleExpression"
  | VhdSubTypeRange -> "VhdSubTypeRange"
  | VhdSubscriptName -> "VhdSubscriptName"
  | VhdSuffixAll -> "VhdSuffixAll"
  | VhdSuffixCharLiteral -> "VhdSuffixCharLiteral"
  | VhdSuffixOpSymbol -> "VhdSuffixOpSymbol"
  | VhdSuffixSimpleName -> "VhdSuffixSimpleName"
  | VhdTargetAggregate -> "VhdTargetAggregate"
  | VhdTargetInvalid -> "VhdTargetInvalid"
  | VhdTargetName -> "VhdTargetName"
  | VhdTargetDotted -> "VhdTargetDotted"
  | VhdTargetNameParameters -> "VhdTargetNameParameters"
  | VhdUnaffected -> "VhdUnaffected"
  | VhdUnboundedArray -> "VhdUnboundedArray"
  | VhdUnknown -> "VhdUnknown"
  | VhdVariableDeclaration -> "VhdVariableDeclaration"
  | VhdWhileLoop -> "VhdWhileLoop"
  | VhdXnorFactor -> "VhdXnorFactor"
  | VhdXnorLogicalExpression -> "VhdXnorLogicalExpression"
  | VhdXorFactor -> "VhdXorFactor"
  | VhdXorLogicalExpression -> "VhdXorLogicalExpression"
  | Vhdalias_declaration -> "Vhdalias_declaration"
  | Vhdarchitecture_body -> "Vhdarchitecture_body"
  | Vhdassertion -> "Vhdassertion"
  | Vhdassertion_statement -> "Vhdassertion_statement"
  | Vhdassociation_element -> "Vhdassociation_element"
  | Vhdattribute_declaration -> "Vhdattribute_declaration"
  | Vhdattribute_name -> "Vhdattribute_name"
  | Vhdattribute_specification -> "Vhdattribute_specification"
  | Vhdbinding_indication -> "Vhdbinding_indication"
  | Vhdblock_configuration -> "Vhdblock_configuration"
  | Vhdblock_statement -> "Vhdblock_statement"
  | Vhdcase_generate_alternative -> "Vhdcase_generate_alternative"
  | Vhdcase_generate_statement -> "Vhdcase_generate_statement"
  | Vhdcase_statement -> "Vhdcase_statement"
  | Vhdcase_statement_alternative -> "Vhdcase_statement_alternative"
  | Vhdcomponent_configuration -> "Vhdcomponent_configuration"
  | Vhdcomponent_declaration -> "Vhdcomponent_declaration"
  | Vhdcomponent_instantiation_statement -> "Vhdcomponent_instantiation_statement"
  | Vhdcomponent_specification -> "Vhdcomponent_specification"
  | Vhdconcurrent_assertion_statement -> "Vhdconcurrent_assertion_statement"
  | Vhdconcurrent_conditional_signal_assignment -> "Vhdconcurrent_conditional_signal_assignment"
  | Vhdconcurrent_procedure_call_statement -> "Vhdconcurrent_procedure_call_statement"
  | Vhdconcurrent_selected_signal_assignment -> "Vhdconcurrent_selected_signal_assignment"
  | Vhdconcurrent_signal_assignment_statement -> "Vhdconcurrent_signal_assignment_statement"
  | Vhdconcurrent_simple_signal_assignment -> "Vhdconcurrent_simple_signal_assignment"
  | Vhdconditional_expression -> "Vhdconditional_expression"
  | Vhdconditional_signal_assignment_statement -> "Vhdconditional_signal_assignment_statement"
  | Vhdconditional_variable_assignment -> "Vhdconditional_variable_assignment"
  | Vhdconditional_waveform -> "Vhdconditional_waveform"
  | Vhdconfiguration_declaration -> "Vhdconfiguration_declaration"
  | Vhdconfiguration_specification -> "Vhdconfiguration_specification"
  | Vhdconstant_declaration -> "Vhdconstant_declaration"
  | Vhdconstrained_array_definition -> "Vhdconstrained_array_definition"
  | Vhdcontext_declaration -> "Vhdcontext_declaration"
  | Vhddesign_unit -> "Vhddesign_unit"
  | Vhdelement_association -> "Vhdelement_association"
  | Vhdelement_declaration -> "Vhdelement_declaration"
  | Vhdentity_declaration -> "Vhdentity_declaration"
  | Vhdentity_designator -> "Vhdentity_designator"
  | Vhdentity_header -> "Vhdentity_header"
  | Vhdentity_specification -> "Vhdentity_specification"
  | Vhdexit_statement -> "Vhdexit_statement"
  | Vhdfile_declaration -> "Vhdfile_declaration"
  | Vhdfor_generate_statement -> "Vhdfor_generate_statement"
  | Vhdfull_type_declaration -> "Vhdfull_type_declaration"
  | Vhdfunction_specification -> "Vhdfunction_specification"
  | Vhdif_generate_statement -> "Vhdif_generate_statement"
  | Vhdif_statement -> "Vhdif_statement"
  | Vhdincomplete_type_declaration -> "Vhdincomplete_type_declaration"
  | Vhdinterface_constant_declaration -> "Vhdinterface_constant_declaration"
  | Vhdinterface_default_declaration -> "Vhdinterface_default_declaration"
  | Vhdinterface_file_declaration -> "Vhdinterface_file_declaration"
  | Vhdinterface_signal_declaration -> "Vhdinterface_signal_declaration"
  | Vhdinterface_variable_declaration -> "Vhdinterface_variable_declaration"
  | Vhdloop_statement -> "Vhdloop_statement"
  | Vhdnext_statement -> "Vhdnext_statement"
  | Vhdnull_statement -> "Vhdnull_statement"
  | Vhdpackage_body -> "Vhdpackage_body"
  | Vhdpackage_declaration -> "Vhdpackage_declaration"
  | Vhdpackage_instantiation -> "Vhdpackage_instantiation"
  | Vhdparameter_specification -> "Vhdparameter_specification"
  | Vhdparsed_file -> "Vhdparsed_file"
  | Vhdphysical_type_definition -> "Vhdphysical_type_definition"
  | Vhdprocedure_call -> "Vhdprocedure_call"
  | Vhdprocedure_call_statement -> "Vhdprocedure_call_statement"
  | Vhdprocedure_specification -> "Vhdprocedure_specification"
  | Vhdprocess_statement -> "Vhdprocess_statement"
  | Vhdrecord_type_definition -> "Vhdrecord_type_definition"
  | Vhdreport_statement -> "Vhdreport_statement"
  | Vhdreturn_statement -> "Vhdreturn_statement"
  | Vhdselected_expression -> "Vhdselected_expression"
  | Vhdselected_signal_assignment_statement -> "Vhdselected_signal_assignment_statement"
  | Vhdselected_variable_assignment -> "Vhdselected_variable_assignment"
  | Vhdselected_waveform -> "Vhdselected_waveform"
  | Vhdsignal_declaration -> "Vhdsignal_declaration"
  | Vhdsignature -> "Vhdsignature"
  | Vhdsimple_signal_assignment_statement -> "Vhdsimple_signal_assignment_statement"
  | Vhdsimple_variable_assignment -> "Vhdsimple_variable_assignment"
  | Vhdsubprogram_body -> "Vhdsubprogram_body"
  | Vhdsubprogram_instantiation -> "Vhdsubprogram_instantiation"
  | Vhdsubtype_declaration -> "Vhdsubtype_declaration"
  | Vhdsubtype_indication -> "Vhdsubtype_indication"
  | Vhdunbounded_array_definition -> "Vhdunbounded_array_definition"
  | Vhdvariable_declaration -> "Vhdvariable_declaration"
  | Vhdwait_statement -> "Vhdwait_statement"
  | Vhdwaveform_element -> "Vhdwaveform_element"
  | Quinvigenuple(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _) -> "unknown"
  | Quattuorvigenuple(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _) -> "unknown"
  | Trevigenuple(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _) -> "unknown"
  | Duovigenuple(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _) -> "unknown"
  | Unvigenuple(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _) -> "unknown"
  | Vigenuple(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _) -> "unknown"
  | Novemdecuple(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _) -> "unknown"
  | Octodecuple(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _) -> "unknown"
  | Septendecuple(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _) -> "unknown"
  | Sexdecuple(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _) -> "unknown"
  | Quindecuple(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _) -> "unknown"
  | Quattuordecuple(_, _, _, _, _, _, _, _, _, _, _, _, _, _) -> "unknown"
  | Tredecuple(_, _, _, _, _, _, _, _, _, _, _, _, _) -> "unknown"
  | Duodecuple(_, _, _, _, _, _, _, _, _, _, _, _) -> "unknown"
  | Undecuple(_, _, _, _, _, _, _, _, _, _, _) -> "unknown"
  | Decuple(_, _, _, _, _, _, _, _, _, _) -> "unknown"
  | Nonuple(_, _, _, _, _, _, _, _, _) -> "unknown"
  | Octuple (_, _, _, _, _, _, _, _) -> "unknown"
  | Septuple (_, _, _, _, _, _, _) -> "unknown"
  | Sextuple (_, _, _, _, _, _) -> "unknown"
  | Quintuple (_, _, _, _, _) -> "unknown"
  | Quadruple (_, _, _, _) -> "unknown"
  | Triple (_, _, _) -> "unknown"
  | Double (_, _) -> "unknown"
  | List _ -> "unknown"
  | Char _ -> "unknown"
  | Real _ -> "unknown"
  | Num _ -> "unknown"
  | Str _ -> "unknown"
  | VhdNone -> "unknown"
