(*
    <vscr - Verilog converter to hls format.>
    Copyright (C) <2011,2012>  <Jonathan Richard Robert Kimmitt>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*)

let copyright () =
Printf.printf "    <%s>  Copyright (C) <2011-2015>  <Jonathan Kimmitt>\n" Sys.argv.(0);
Printf.printf "    <VHDL Front-End>  Copyright (C) <2008-2010>  <TIMA Laboratory - VDS Team>\n";
Printf.printf "    <Verilog Grammar>  Copyright (C) <2003-2011>  <Wilson Snyder - <http://www.veripool.org/>>\n";
Printf.printf "    <Theorem Proving Library>  Copyright (C) <2003-2007>  <John Harrison>\n";
Printf.printf "    <Bdd Library>  Copyright (C) <2008-2009>  <Jean-Christophe Filliatre>\n";
Printf.printf "    This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'.\n";
Printf.printf "    This is free software, and you are welcome to redistribute it\n";
Printf.printf "    under certain conditions; type `show c' for details.\n"

let license = function
  | "c"
  | "copying" ->
Printf.printf "                    GNU GENERAL PUBLIC LICENSE\n";
Printf.printf "                       Version 3, 29 June 2007\n";
Printf.printf "\n";
Printf.printf " Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/>\n";
Printf.printf " Everyone is permitted to copy and distribute verbatim copies\n";
Printf.printf " of this license document, but changing it is not allowed.\n";
Printf.printf "\n";
Printf.printf "                            Preamble\n";
Printf.printf "\n";
Printf.printf "  The GNU General Public License is a free, copyleft license for\n";
Printf.printf "software and other kinds of works.\n";
Printf.printf "\n";
Printf.printf "  The licenses for most software and other practical works are designed\n";
Printf.printf "to take away your freedom to share and change the works.  By contrast,\n";
Printf.printf "the GNU General Public License is intended to guarantee your freedom to\n";
Printf.printf "share and change all versions of a program--to make sure it remains free\n";
Printf.printf "software for all its users.  We, the Free Software Foundation, use the\n";
Printf.printf "GNU General Public License for most of our software; it applies also to\n";
Printf.printf "any other work released this way by its authors.  You can apply it to\n";
Printf.printf "your programs, too.\n";
Printf.printf "\n";
Printf.printf "  When we speak of free software, we are referring to freedom, not\n";
Printf.printf "price.  Our General Public Licenses are designed to make sure that you\n";
Printf.printf "have the freedom to distribute copies of free software (and charge for\n";
Printf.printf "them if you wish), that you receive source code or can get it if you\n";
Printf.printf "want it, that you can change the software or use pieces of it in new\n";
Printf.printf "free programs, and that you know you can do these things.\n";
Printf.printf "\n";
Printf.printf "  To protect your rights, we need to prevent others from denying you\n";
Printf.printf "these rights or asking you to surrender the rights.  Therefore, you have\n";
Printf.printf "certain responsibilities if you distribute copies of the software, or if\n";
Printf.printf "you modify it: responsibilities to respect the freedom of others.\n";
Printf.printf "\n";
Printf.printf "  For example, if you distribute copies of such a program, whether\n";
Printf.printf "gratis or for a fee, you must pass on to the recipients the same\n";
Printf.printf "freedoms that you received.  You must make sure that they, too, receive\n";
Printf.printf "or can get the source code.  And you must show them these terms so they\n";
Printf.printf "know their rights.\n";
Printf.printf "\n";
Printf.printf "  Developers that use the GNU GPL protect your rights with two steps:\n";
Printf.printf "(1) assert copyright on the software, and (2) offer you this License\n";
Printf.printf "giving you legal permission to copy, distribute and/or modify it.\n";
Printf.printf "\n";
Printf.printf "  For the developers' and authors' protection, the GPL clearly explains\n";
Printf.printf "that there is no warranty for this free software.  For both users' and\n";
Printf.printf "authors' sake, the GPL requires that modified versions be marked as\n";
Printf.printf "changed, so that their problems will not be attributed erroneously to\n";
Printf.printf "authors of previous versions.\n";
Printf.printf "\n";
Printf.printf "  Some devices are designed to deny users access to install or run\n";
Printf.printf "modified versions of the software inside them, although the manufacturer\n";
Printf.printf "can do so.  This is fundamentally incompatible with the aim of\n";
Printf.printf "protecting users' freedom to change the software.  The systematic\n";
Printf.printf "pattern of such abuse occurs in the area of products for individuals to\n";
Printf.printf "use, which is precisely where it is most unacceptable.  Therefore, we\n";
Printf.printf "have designed this version of the GPL to prohibit the practice for those\n";
Printf.printf "products.  If such problems arise substantially in other domains, we\n";
Printf.printf "stand ready to extend this provision to those domains in future versions\n";
Printf.printf "of the GPL, as needed to protect the freedom of users.\n";
Printf.printf "\n";
Printf.printf "  Finally, every program is threatened constantly by software patents.\n";
Printf.printf "States should not allow patents to restrict development and use of\n";
Printf.printf "software on general-purpose computers, but in those that do, we wish to\n";
Printf.printf "avoid the special danger that patents applied to a free program could\n";
Printf.printf "make it effectively proprietary.  To prevent this, the GPL assures that\n";
Printf.printf "patents cannot be used to render the program non-free.\n";
Printf.printf "\n";
Printf.printf "  The precise terms and conditions for copying, distribution and\n";
Printf.printf "modification follow.\n";
Printf.printf "\n";
Printf.printf "                       TERMS AND CONDITIONS\n";
Printf.printf "\n";
Printf.printf "  0. Definitions.\n";
Printf.printf "\n";
Printf.printf "  \"This License\" refers to version 3 of the GNU General Public License.\n";
Printf.printf "\n";
Printf.printf "  \"Copyright\" also means copyright-like laws that apply to other kinds of\n";
Printf.printf "works, such as semiconductor masks.\n";
Printf.printf "\n";
Printf.printf "  \"The Program\" refers to any copyrightable work licensed under this\n";
Printf.printf "License.  Each licensee is addressed as \"you\".  \"Licensees\" and\n";
Printf.printf "\"recipients\" may be individuals or organizations.\n";
Printf.printf "\n";
Printf.printf "  To \"modify\" a work means to copy from or adapt all or part of the work\n";
Printf.printf "in a fashion requiring copyright permission, other than the making of an\n";
Printf.printf "exact copy.  The resulting work is called a \"modified version\" of the\n";
Printf.printf "earlier work or a work \"based on\" the earlier work.\n";
Printf.printf "\n";
Printf.printf "  A \"covered work\" means either the unmodified Program or a work based\n";
Printf.printf "on the Program.\n";
Printf.printf "\n";
Printf.printf "  To \"propagate\" a work means to do anything with it that, without\n";
Printf.printf "permission, would make you directly or secondarily liable for\n";
Printf.printf "infringement under applicable copyright law, except executing it on a\n";
Printf.printf "computer or modifying a private copy.  Propagation includes copying,\n";
Printf.printf "distribution (with or without modification), making available to the\n";
Printf.printf "public, and in some countries other activities as well.\n";
Printf.printf "\n";
Printf.printf "  To \"convey\" a work means any kind of propagation that enables other\n";
Printf.printf "parties to make or receive copies.  Mere interaction with a user through\n";
Printf.printf "a computer network, with no transfer of a copy, is not conveying.\n";
Printf.printf "\n";
Printf.printf "  An interactive user interface displays \"Appropriate Legal Notices\"\n";
Printf.printf "to the extent that it includes a convenient and prominently visible\n";
Printf.printf "feature that (1) displays an appropriate copyright notice, and (2)\n";
Printf.printf "tells the user that there is no warranty for the work (except to the\n";
Printf.printf "extent that warranties are provided), that licensees may convey the\n";
Printf.printf "work under this License, and how to view a copy of this License.  If\n";
Printf.printf "the interface presents a list of user commands or options, such as a\n";
Printf.printf "menu, a prominent item in the list meets this criterion.\n";
Printf.printf "\n";
Printf.printf "  1. Source Code.\n";
Printf.printf "\n";
Printf.printf "  The \"source code\" for a work means the preferred form of the work\n";
Printf.printf "for making modifications to it.  \"Object code\" means any non-source\n";
Printf.printf "form of a work.\n";
Printf.printf "\n";
Printf.printf "  A \"Standard Interface\" means an interface that either is an official\n";
Printf.printf "standard defined by a recognized standards body, or, in the case of\n";
Printf.printf "interfaces specified for a particular programming language, one that\n";
Printf.printf "is widely used among developers working in that language.\n";
Printf.printf "\n";
Printf.printf "  The \"System Libraries\" of an executable work include anything, other\n";
Printf.printf "than the work as a whole, that (a) is included in the normal form of\n";
Printf.printf "packaging a Major Component, but which is not part of that Major\n";
Printf.printf "Component, and (b) serves only to enable use of the work with that\n";
Printf.printf "Major Component, or to implement a Standard Interface for which an\n";
Printf.printf "implementation is available to the public in source code form.  A\n";
Printf.printf "\"Major Component\", in this context, means a major essential component\n";
Printf.printf "(kernel, window system, and so on) of the specific operating system\n";
Printf.printf "(if any) on which the executable work runs, or a compiler used to\n";
Printf.printf "produce the work, or an object code interpreter used to run it.\n";
Printf.printf "\n";
Printf.printf "  The \"Corresponding Source\" for a work in object code form means all\n";
Printf.printf "the source code needed to generate, install, and (for an executable\n";
Printf.printf "work) run the object code and to modify the work, including scripts to\n";
Printf.printf "control those activities.  However, it does not include the work's\n";
Printf.printf "System Libraries, or general-purpose tools or generally available free\n";
Printf.printf "programs which are used unmodified in performing those activities but\n";
Printf.printf "which are not part of the work.  For example, Corresponding Source\n";
Printf.printf "includes interface definition files associated with source files for\n";
Printf.printf "the work, and the source code for shared libraries and dynamically\n";
Printf.printf "linked subprograms that the work is specifically designed to require,\n";
Printf.printf "such as by intimate data communication or control flow between those\n";
Printf.printf "subprograms and other parts of the work.\n";
Printf.printf "\n";
Printf.printf "  The Corresponding Source need not include anything that users\n";
Printf.printf "can regenerate automatically from other parts of the Corresponding\n";
Printf.printf "Source.\n";
Printf.printf "\n";
Printf.printf "  The Corresponding Source for a work in source code form is that\n";
Printf.printf "same work.\n";
Printf.printf "\n";
Printf.printf "  2. Basic Permissions.\n";
Printf.printf "\n";
Printf.printf "  All rights granted under this License are granted for the term of\n";
Printf.printf "copyright on the Program, and are irrevocable provided the stated\n";
Printf.printf "conditions are met.  This License explicitly affirms your unlimited\n";
Printf.printf "permission to run the unmodified Program.  The output from running a\n";
Printf.printf "covered work is covered by this License only if the output, given its\n";
Printf.printf "content, constitutes a covered work.  This License acknowledges your\n";
Printf.printf "rights of fair use or other equivalent, as provided by copyright law.\n";
Printf.printf "\n";
Printf.printf "  You may make, run and propagate covered works that you do not\n";
Printf.printf "convey, without conditions so long as your license otherwise remains\n";
Printf.printf "in force.  You may convey covered works to others for the sole purpose\n";
Printf.printf "of having them make modifications exclusively for you, or provide you\n";
Printf.printf "with facilities for running those works, provided that you comply with\n";
Printf.printf "the terms of this License in conveying all material for which you do\n";
Printf.printf "not control copyright.  Those thus making or running the covered works\n";
Printf.printf "for you must do so exclusively on your behalf, under your direction\n";
Printf.printf "and control, on terms that prohibit them from making any copies of\n";
Printf.printf "your copyrighted material outside their relationship with you.\n";
Printf.printf "\n";
Printf.printf "  Conveying under any other circumstances is permitted solely under\n";
Printf.printf "the conditions stated below.  Sublicensing is not allowed; section 10\n";
Printf.printf "makes it unnecessary.\n";
Printf.printf "\n";
Printf.printf "  3. Protecting Users' Legal Rights From Anti-Circumvention Law.\n";
Printf.printf "\n";
Printf.printf "  No covered work shall be deemed part of an effective technological\n";
Printf.printf "measure under any applicable law fulfilling obligations under article\n";
Printf.printf "11 of the WIPO copyright treaty adopted on 20 December 1996, or\n";
Printf.printf "similar laws prohibiting or restricting circumvention of such\n";
Printf.printf "measures.\n";
Printf.printf "\n";
Printf.printf "  When you convey a covered work, you waive any legal power to forbid\n";
Printf.printf "circumvention of technological measures to the extent such circumvention\n";
Printf.printf "is effected by exercising rights under this License with respect to\n";
Printf.printf "the covered work, and you disclaim any intention to limit operation or\n";
Printf.printf "modification of the work as a means of enforcing, against the work's\n";
Printf.printf "users, your or third parties' legal rights to forbid circumvention of\n";
Printf.printf "technological measures.\n";
Printf.printf "\n";
Printf.printf "  4. Conveying Verbatim Copies.\n";
Printf.printf "\n";
Printf.printf "  You may convey verbatim copies of the Program's source code as you\n";
Printf.printf "receive it, in any medium, provided that you conspicuously and\n";
Printf.printf "appropriately publish on each copy an appropriate copyright notice;\n";
Printf.printf "keep intact all notices stating that this License and any\n";
Printf.printf "non-permissive terms added in accord with section 7 apply to the code;\n";
Printf.printf "keep intact all notices of the absence of any warranty; and give all\n";
Printf.printf "recipients a copy of this License along with the Program.\n";
Printf.printf "\n";
Printf.printf "  You may charge any price or no price for each copy that you convey,\n";
Printf.printf "and you may offer support or warranty protection for a fee.\n";
Printf.printf "\n";
Printf.printf "  5. Conveying Modified Source Versions.\n";
Printf.printf "\n";
Printf.printf "  You may convey a work based on the Program, or the modifications to\n";
Printf.printf "produce it from the Program, in the form of source code under the\n";
Printf.printf "terms of section 4, provided that you also meet all of these conditions:\n";
Printf.printf "\n";
Printf.printf "    a) The work must carry prominent notices stating that you modified\n";
Printf.printf "    it, and giving a relevant date.\n";
Printf.printf "\n";
Printf.printf "    b) The work must carry prominent notices stating that it is\n";
Printf.printf "    released under this License and any conditions added under section\n";
Printf.printf "    7.  This requirement modifies the requirement in section 4 to\n";
Printf.printf "    \"keep intact all notices\".\n";
Printf.printf "\n";
Printf.printf "    c) You must license the entire work, as a whole, under this\n";
Printf.printf "    License to anyone who comes into possession of a copy.  This\n";
Printf.printf "    License will therefore apply, along with any applicable section 7\n";
Printf.printf "    additional terms, to the whole of the work, and all its parts,\n";
Printf.printf "    regardless of how they are packaged.  This License gives no\n";
Printf.printf "    permission to license the work in any other way, but it does not\n";
Printf.printf "    invalidate such permission if you have separately received it.\n";
Printf.printf "\n";
Printf.printf "    d) If the work has interactive user interfaces, each must display\n";
Printf.printf "    Appropriate Legal Notices; however, if the Program has interactive\n";
Printf.printf "    interfaces that do not display Appropriate Legal Notices, your\n";
Printf.printf "    work need not make them do so.\n";
Printf.printf "\n";
Printf.printf "  A compilation of a covered work with other separate and independent\n";
Printf.printf "works, which are not by their nature extensions of the covered work,\n";
Printf.printf "and which are not combined with it such as to form a larger program,\n";
Printf.printf "in or on a volume of a storage or distribution medium, is called an\n";
Printf.printf "\"aggregate\" if the compilation and its resulting copyright are not\n";
Printf.printf "used to limit the access or legal rights of the compilation's users\n";
Printf.printf "beyond what the individual works permit.  Inclusion of a covered work\n";
Printf.printf "in an aggregate does not cause this License to apply to the other\n";
Printf.printf "parts of the aggregate.\n";
Printf.printf "\n";
Printf.printf "  6. Conveying Non-Source Forms.\n";
Printf.printf "\n";
Printf.printf "  You may convey a covered work in object code form under the terms\n";
Printf.printf "of sections 4 and 5, provided that you also convey the\n";
Printf.printf "machine-readable Corresponding Source under the terms of this License,\n";
Printf.printf "in one of these ways:\n";
Printf.printf "\n";
Printf.printf "    a) Convey the object code in, or embodied in, a physical product\n";
Printf.printf "    (including a physical distribution medium), accompanied by the\n";
Printf.printf "    Corresponding Source fixed on a durable physical medium\n";
Printf.printf "    customarily used for software interchange.\n";
Printf.printf "\n";
Printf.printf "    b) Convey the object code in, or embodied in, a physical product\n";
Printf.printf "    (including a physical distribution medium), accompanied by a\n";
Printf.printf "    written offer, valid for at least three years and valid for as\n";
Printf.printf "    long as you offer spare parts or customer support for that product\n";
Printf.printf "    model, to give anyone who possesses the object code either (1) a\n";
Printf.printf "    copy of the Corresponding Source for all the software in the\n";
Printf.printf "    product that is covered by this License, on a durable physical\n";
Printf.printf "    medium customarily used for software interchange, for a price no\n";
Printf.printf "    more than your reasonable cost of physically performing this\n";
Printf.printf "    conveying of source, or (2) access to copy the\n";
Printf.printf "    Corresponding Source from a network server at no charge.\n";
Printf.printf "\n";
Printf.printf "    c) Convey individual copies of the object code with a copy of the\n";
Printf.printf "    written offer to provide the Corresponding Source.  This\n";
Printf.printf "    alternative is allowed only occasionally and noncommercially, and\n";
Printf.printf "    only if you received the object code with such an offer, in accord\n";
Printf.printf "    with subsection 6b.\n";
Printf.printf "\n";
Printf.printf "    d) Convey the object code by offering access from a designated\n";
Printf.printf "    place (gratis or for a charge), and offer equivalent access to the\n";
Printf.printf "    Corresponding Source in the same way through the same place at no\n";
Printf.printf "    further charge.  You need not require recipients to copy the\n";
Printf.printf "    Corresponding Source along with the object code.  If the place to\n";
Printf.printf "    copy the object code is a network server, the Corresponding Source\n";
Printf.printf "    may be on a different server (operated by you or a third party)\n";
Printf.printf "    that supports equivalent copying facilities, provided you maintain\n";
Printf.printf "    clear directions next to the object code saying where to find the\n";
Printf.printf "    Corresponding Source.  Regardless of what server hosts the\n";
Printf.printf "    Corresponding Source, you remain obligated to ensure that it is\n";
Printf.printf "    available for as long as needed to satisfy these requirements.\n";
Printf.printf "\n";
Printf.printf "    e) Convey the object code using peer-to-peer transmission, provided\n";
Printf.printf "    you inform other peers where the object code and Corresponding\n";
Printf.printf "    Source of the work are being offered to the general public at no\n";
Printf.printf "    charge under subsection 6d.\n";
Printf.printf "\n";
Printf.printf "  A separable portion of the object code, whose source code is excluded\n";
Printf.printf "from the Corresponding Source as a System Library, need not be\n";
Printf.printf "included in conveying the object code work.\n";
Printf.printf "\n";
Printf.printf "  A \"User Product\" is either (1) a \"consumer product\", which means any\n";
Printf.printf "tangible personal property which is normally used for personal, family,\n";
Printf.printf "or household purposes, or (2) anything designed or sold for incorporation\n";
Printf.printf "into a dwelling.  In determining whether a product is a consumer product,\n";
Printf.printf "doubtful cases shall be resolved in favor of coverage.  For a particular\n";
Printf.printf "product received by a particular user, \"normally used\" refers to a\n";
Printf.printf "typical or common use of that class of product, regardless of the status\n";
Printf.printf "of the particular user or of the way in which the particular user\n";
Printf.printf "actually uses, or expects or is expected to use, the product.  A product\n";
Printf.printf "is a consumer product regardless of whether the product has substantial\n";
Printf.printf "commercial, industrial or non-consumer uses, unless such uses represent\n";
Printf.printf "the only significant mode of use of the product.\n";
Printf.printf "\n";
Printf.printf "  \"Installation Information\" for a User Product means any methods,\n";
Printf.printf "procedures, authorization keys, or other information required to install\n";
Printf.printf "and execute modified versions of a covered work in that User Product from\n";
Printf.printf "a modified version of its Corresponding Source.  The information must\n";
Printf.printf "suffice to ensure that the continued functioning of the modified object\n";
Printf.printf "code is in no case prevented or interfered with solely because\n";
Printf.printf "modification has been made.\n";
Printf.printf "\n";
Printf.printf "  If you convey an object code work under this section in, or with, or\n";
Printf.printf "specifically for use in, a User Product, and the conveying occurs as\n";
Printf.printf "part of a transaction in which the right of possession and use of the\n";
Printf.printf "User Product is transferred to the recipient in perpetuity or for a\n";
Printf.printf "fixed term (regardless of how the transaction is characterized), the\n";
Printf.printf "Corresponding Source conveyed under this section must be accompanied\n";
Printf.printf "by the Installation Information.  But this requirement does not apply\n";
Printf.printf "if neither you nor any third party retains the ability to install\n";
Printf.printf "modified object code on the User Product (for example, the work has\n";
Printf.printf "been installed in ROM).\n";
Printf.printf "\n";
Printf.printf "  The requirement to provide Installation Information does not include a\n";
Printf.printf "requirement to continue to provide support service, warranty, or updates\n";
Printf.printf "for a work that has been modified or installed by the recipient, or for\n";
Printf.printf "the User Product in which it has been modified or installed.  Access to a\n";
Printf.printf "network may be denied when the modification itself materially and\n";
Printf.printf "adversely affects the operation of the network or violates the rules and\n";
Printf.printf "protocols for communication across the network.\n";
Printf.printf "\n";
Printf.printf "  Corresponding Source conveyed, and Installation Information provided,\n";
Printf.printf "in accord with this section must be in a format that is publicly\n";
Printf.printf "documented (and with an implementation available to the public in\n";
Printf.printf "source code form), and must require no special password or key for\n";
Printf.printf "unpacking, reading or copying.\n";
Printf.printf "\n";
Printf.printf "  7. Additional Terms.\n";
Printf.printf "\n";
Printf.printf "  \"Additional permissions\" are terms that supplement the terms of this\n";
Printf.printf "License by making exceptions from one or more of its conditions.\n";
Printf.printf "Additional permissions that are applicable to the entire Program shall\n";
Printf.printf "be treated as though they were included in this License, to the extent\n";
Printf.printf "that they are valid under applicable law.  If additional permissions\n";
Printf.printf "apply only to part of the Program, that part may be used separately\n";
Printf.printf "under those permissions, but the entire Program remains governed by\n";
Printf.printf "this License without regard to the additional permissions.\n";
Printf.printf "\n";
Printf.printf "  When you convey a copy of a covered work, you may at your option\n";
Printf.printf "remove any additional permissions from that copy, or from any part of\n";
Printf.printf "it.  (Additional permissions may be written to require their own\n";
Printf.printf "removal in certain cases when you modify the work.)  You may place\n";
Printf.printf "additional permissions on material, added by you to a covered work,\n";
Printf.printf "for which you have or can give appropriate copyright permission.\n";
Printf.printf "\n";
Printf.printf "  Notwithstanding any other provision of this License, for material you\n";
Printf.printf "add to a covered work, you may (if authorized by the copyright holders of\n";
Printf.printf "that material) supplement the terms of this License with terms:\n";
Printf.printf "\n";
Printf.printf "    a) Disclaiming warranty or limiting liability differently from the\n";
Printf.printf "    terms of sections 15 and 16 of this License; or\n";
Printf.printf "\n";
Printf.printf "    b) Requiring preservation of specified reasonable legal notices or\n";
Printf.printf "    author attributions in that material or in the Appropriate Legal\n";
Printf.printf "    Notices displayed by works containing it; or\n";
Printf.printf "\n";
Printf.printf "    c) Prohibiting misrepresentation of the origin of that material, or\n";
Printf.printf "    requiring that modified versions of such material be marked in\n";
Printf.printf "    reasonable ways as different from the original version; or\n";
Printf.printf "\n";
Printf.printf "    d) Limiting the use for publicity purposes of names of licensors or\n";
Printf.printf "    authors of the material; or\n";
Printf.printf "\n";
Printf.printf "    e) Declining to grant rights under trademark law for use of some\n";
Printf.printf "    trade names, trademarks, or service marks; or\n";
Printf.printf "\n";
Printf.printf "    f) Requiring indemnification of licensors and authors of that\n";
Printf.printf "    material by anyone who conveys the material (or modified versions of\n";
Printf.printf "    it) with contractual assumptions of liability to the recipient, for\n";
Printf.printf "    any liability that these contractual assumptions directly impose on\n";
Printf.printf "    those licensors and authors.\n";
Printf.printf "\n";
Printf.printf "  All other non-permissive additional terms are considered \"further\n";
Printf.printf "restrictions\" within the meaning of section 10.  If the Program as you\n";
Printf.printf "received it, or any part of it, contains a notice stating that it is\n";
Printf.printf "governed by this License along with a term that is a further\n";
Printf.printf "restriction, you may remove that term.  If a license document contains\n";
Printf.printf "a further restriction but permits relicensing or conveying under this\n";
Printf.printf "License, you may add to a covered work material governed by the terms\n";
Printf.printf "of that license document, provided that the further restriction does\n";
Printf.printf "not survive such relicensing or conveying.\n";
Printf.printf "\n";
Printf.printf "  If you add terms to a covered work in accord with this section, you\n";
Printf.printf "must place, in the relevant source files, a statement of the\n";
Printf.printf "additional terms that apply to those files, or a notice indicating\n";
Printf.printf "where to find the applicable terms.\n";
Printf.printf "\n";
Printf.printf "  Additional terms, permissive or non-permissive, may be stated in the\n";
Printf.printf "form of a separately written license, or stated as exceptions;\n";
Printf.printf "the above requirements apply either way.\n";
Printf.printf "\n";
Printf.printf "  8. Termination.\n";
Printf.printf "\n";
Printf.printf "  You may not propagate or modify a covered work except as expressly\n";
Printf.printf "provided under this License.  Any attempt otherwise to propagate or\n";
Printf.printf "modify it is void, and will automatically terminate your rights under\n";
Printf.printf "this License (including any patent licenses granted under the third\n";
Printf.printf "paragraph of section 11).\n";
Printf.printf "\n";
Printf.printf "  However, if you cease all violation of this License, then your\n";
Printf.printf "license from a particular copyright holder is reinstated (a)\n";
Printf.printf "provisionally, unless and until the copyright holder explicitly and\n";
Printf.printf "finally terminates your license, and (b) permanently, if the copyright\n";
Printf.printf "holder fails to notify you of the violation by some reasonable means\n";
Printf.printf "prior to 60 days after the cessation.\n";
Printf.printf "\n";
Printf.printf "  Moreover, your license from a particular copyright holder is\n";
Printf.printf "reinstated permanently if the copyright holder notifies you of the\n";
Printf.printf "violation by some reasonable means, this is the first time you have\n";
Printf.printf "received notice of violation of this License (for any work) from that\n";
Printf.printf "copyright holder, and you cure the violation prior to 30 days after\n";
Printf.printf "your receipt of the notice.\n";
Printf.printf "\n";
Printf.printf "  Termination of your rights under this section does not terminate the\n";
Printf.printf "licenses of parties who have received copies or rights from you under\n";
Printf.printf "this License.  If your rights have been terminated and not permanently\n";
Printf.printf "reinstated, you do not qualify to receive new licenses for the same\n";
Printf.printf "material under section 10.\n";
Printf.printf "\n";
Printf.printf "  9. Acceptance Not Required for Having Copies.\n";
Printf.printf "\n";
Printf.printf "  You are not required to accept this License in order to receive or\n";
Printf.printf "run a copy of the Program.  Ancillary propagation of a covered work\n";
Printf.printf "occurring solely as a consequence of using peer-to-peer transmission\n";
Printf.printf "to receive a copy likewise does not require acceptance.  However,\n";
Printf.printf "nothing other than this License grants you permission to propagate or\n";
Printf.printf "modify any covered work.  These actions infringe copyright if you do\n";
Printf.printf "not accept this License.  Therefore, by modifying or propagating a\n";
Printf.printf "covered work, you indicate your acceptance of this License to do so.\n";
Printf.printf "\n";
Printf.printf "  10. Automatic Licensing of Downstream Recipients.\n";
Printf.printf "\n";
Printf.printf "  Each time you convey a covered work, the recipient automatically\n";
Printf.printf "receives a license from the original licensors, to run, modify and\n";
Printf.printf "propagate that work, subject to this License.  You are not responsible\n";
Printf.printf "for enforcing compliance by third parties with this License.\n";
Printf.printf "\n";
Printf.printf "  An \"entity transaction\" is a transaction transferring control of an\n";
Printf.printf "organization, or substantially all assets of one, or subdividing an\n";
Printf.printf "organization, or merging organizations.  If propagation of a covered\n";
Printf.printf "work results from an entity transaction, each party to that\n";
Printf.printf "transaction who receives a copy of the work also receives whatever\n";
Printf.printf "licenses to the work the party's predecessor in interest had or could\n";
Printf.printf "give under the previous paragraph, plus a right to possession of the\n";
Printf.printf "Corresponding Source of the work from the predecessor in interest, if\n";
Printf.printf "the predecessor has it or can get it with reasonable efforts.\n";
Printf.printf "\n";
Printf.printf "  You may not impose any further restrictions on the exercise of the\n";
Printf.printf "rights granted or affirmed under this License.  For example, you may\n";
Printf.printf "not impose a license fee, royalty, or other charge for exercise of\n";
Printf.printf "rights granted under this License, and you may not initiate litigation\n";
Printf.printf "(including a cross-claim or counterclaim in a lawsuit) alleging that\n";
Printf.printf "any patent claim is infringed by making, using, selling, offering for\n";
Printf.printf "sale, or importing the Program or any portion of it.\n";
Printf.printf "\n";
Printf.printf "  11. Patents.\n";
Printf.printf "\n";
Printf.printf "  A \"contributor\" is a copyright holder who authorizes use under this\n";
Printf.printf "License of the Program or a work on which the Program is based.  The\n";
Printf.printf "work thus licensed is called the contributor's \"contributor version\".\n";
Printf.printf "\n";
Printf.printf "  A contributor's \"essential patent claims\" are all patent claims\n";
Printf.printf "owned or controlled by the contributor, whether already acquired or\n";
Printf.printf "hereafter acquired, that would be infringed by some manner, permitted\n";
Printf.printf "by this License, of making, using, or selling its contributor version,\n";
Printf.printf "but do not include claims that would be infringed only as a\n";
Printf.printf "consequence of further modification of the contributor version.  For\n";
Printf.printf "purposes of this definition, \"control\" includes the right to grant\n";
Printf.printf "patent sublicenses in a manner consistent with the requirements of\n";
Printf.printf "this License.\n";
Printf.printf "\n";
Printf.printf "  Each contributor grants you a non-exclusive, worldwide, royalty-free\n";
Printf.printf "patent license under the contributor's essential patent claims, to\n";
Printf.printf "make, use, sell, offer for sale, import and otherwise run, modify and\n";
Printf.printf "propagate the contents of its contributor version.\n";
Printf.printf "\n";
Printf.printf "  In the following three paragraphs, a \"patent license\" is any express\n";
Printf.printf "agreement or commitment, however denominated, not to enforce a patent\n";
Printf.printf "(such as an express permission to practice a patent or covenant not to\n";
Printf.printf "sue for patent infringement).  To \"grant\" such a patent license to a\n";
Printf.printf "party means to make such an agreement or commitment not to enforce a\n";
Printf.printf "patent against the party.\n";
Printf.printf "\n";
Printf.printf "  If you convey a covered work, knowingly relying on a patent license,\n";
Printf.printf "and the Corresponding Source of the work is not available for anyone\n";
Printf.printf "to copy, free of charge and under the terms of this License, through a\n";
Printf.printf "publicly available network server or other readily accessible means,\n";
Printf.printf "then you must either (1) cause the Corresponding Source to be so\n";
Printf.printf "available, or (2) arrange to deprive yourself of the benefit of the\n";
Printf.printf "patent license for this particular work, or (3) arrange, in a manner\n";
Printf.printf "consistent with the requirements of this License, to extend the patent\n";
Printf.printf "license to downstream recipients.  \"Knowingly relying\" means you have\n";
Printf.printf "actual knowledge that, but for the patent license, your conveying the\n";
Printf.printf "covered work in a country, or your recipient's use of the covered work\n";
Printf.printf "in a country, would infringe one or more identifiable patents in that\n";
Printf.printf "country that you have reason to believe are valid.\n";
Printf.printf "\n";
Printf.printf "  If, pursuant to or in connection with a single transaction or\n";
Printf.printf "arrangement, you convey, or propagate by procuring conveyance of, a\n";
Printf.printf "covered work, and grant a patent license to some of the parties\n";
Printf.printf "receiving the covered work authorizing them to use, propagate, modify\n";
Printf.printf "or convey a specific copy of the covered work, then the patent license\n";
Printf.printf "you grant is automatically extended to all recipients of the covered\n";
Printf.printf "work and works based on it.\n";
Printf.printf "\n";
Printf.printf "  A patent license is \"discriminatory\" if it does not include within\n";
Printf.printf "the scope of its coverage, prohibits the exercise of, or is\n";
Printf.printf "conditioned on the non-exercise of one or more of the rights that are\n";
Printf.printf "specifically granted under this License.  You may not convey a covered\n";
Printf.printf "work if you are a party to an arrangement with a third party that is\n";
Printf.printf "in the business of distributing software, under which you make payment\n";
Printf.printf "to the third party based on the extent of your activity of conveying\n";
Printf.printf "the work, and under which the third party grants, to any of the\n";
Printf.printf "parties who would receive the covered work from you, a discriminatory\n";
Printf.printf "patent license (a) in connection with copies of the covered work\n";
Printf.printf "conveyed by you (or copies made from those copies), or (b) primarily\n";
Printf.printf "for and in connection with specific products or compilations that\n";
Printf.printf "contain the covered work, unless you entered into that arrangement,\n";
Printf.printf "or that patent license was granted, prior to 28 March 2007.\n";
Printf.printf "\n";
Printf.printf "  Nothing in this License shall be construed as excluding or limiting\n";
Printf.printf "any implied license or other defenses to infringement that may\n";
Printf.printf "otherwise be available to you under applicable patent law.\n";
Printf.printf "\n";
Printf.printf "  12. No Surrender of Others' Freedom.\n";
Printf.printf "\n";
Printf.printf "  If conditions are imposed on you (whether by court order, agreement or\n";
Printf.printf "otherwise) that contradict the conditions of this License, they do not\n";
Printf.printf "excuse you from the conditions of this License.  If you cannot convey a\n";
Printf.printf "covered work so as to satisfy simultaneously your obligations under this\n";
Printf.printf "License and any other pertinent obligations, then as a consequence you may\n";
Printf.printf "not convey it at all.  For example, if you agree to terms that obligate you\n";
Printf.printf "to collect a royalty for further conveying from those to whom you convey\n";
Printf.printf "the Program, the only way you could satisfy both those terms and this\n";
Printf.printf "License would be to refrain entirely from conveying the Program.\n";
Printf.printf "\n";
Printf.printf "  13. Use with the GNU Affero General Public License.\n";
Printf.printf "\n";
Printf.printf "  Notwithstanding any other provision of this License, you have\n";
Printf.printf "permission to link or combine any covered work with a work licensed\n";
Printf.printf "under version 3 of the GNU Affero General Public License into a single\n";
Printf.printf "combined work, and to convey the resulting work.  The terms of this\n";
Printf.printf "License will continue to apply to the part which is the covered work,\n";
Printf.printf "but the special requirements of the GNU Affero General Public License,\n";
Printf.printf "section 13, concerning interaction through a network will apply to the\n";
Printf.printf "combination as such.\n";
Printf.printf "\n";
Printf.printf "  14. Revised Versions of this License.\n";
Printf.printf "\n";
Printf.printf "  The Free Software Foundation may publish revised and/or new versions of\n";
Printf.printf "the GNU General Public License from time to time.  Such new versions will\n";
Printf.printf "be similar in spirit to the present version, but may differ in detail to\n";
Printf.printf "address new problems or concerns.\n";
Printf.printf "\n";
Printf.printf "  Each version is given a distinguishing version number.  If the\n";
Printf.printf "Program specifies that a certain numbered version of the GNU General\n";
Printf.printf "Public License \"or any later version\" applies to it, you have the\n";
Printf.printf "option of following the terms and conditions either of that numbered\n";
Printf.printf "version or of any later version published by the Free Software\n";
Printf.printf "Foundation.  If the Program does not specify a version number of the\n";
Printf.printf "GNU General Public License, you may choose any version ever published\n";
Printf.printf "by the Free Software Foundation.\n";
Printf.printf "\n";
Printf.printf "  If the Program specifies that a proxy can decide which future\n";
Printf.printf "versions of the GNU General Public License can be used, that proxy's\n";
Printf.printf "public statement of acceptance of a version permanently authorizes you\n";
Printf.printf "to choose that version for the Program.\n";
Printf.printf "\n";
Printf.printf "  Later license versions may give you additional or different\n";
Printf.printf "permissions.  However, no additional obligations are imposed on any\n";
Printf.printf "author or copyright holder as a result of your choosing to follow a\n";
Printf.printf "later version.\n";
Printf.printf "\n";
  | "w"
  | "warranty" ->
Printf.printf "  15. Disclaimer of Warranty.\n";
Printf.printf "\n";
Printf.printf "  THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY\n";
Printf.printf "APPLICABLE LAW.  EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT\n";
Printf.printf "HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM \"AS IS\" WITHOUT WARRANTY\n";
Printf.printf "OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO,\n";
Printf.printf "THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR\n";
Printf.printf "PURPOSE.  THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM\n";
Printf.printf "IS WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF\n";
Printf.printf "ALL NECESSARY SERVICING, REPAIR OR CORRECTION.\n";
Printf.printf "\n";
Printf.printf "  16. Limitation of Liability.\n";
Printf.printf "\n";
Printf.printf "  IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING\n";
Printf.printf "WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR CONVEYS\n";
Printf.printf "THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY\n";
Printf.printf "GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE\n";
Printf.printf "USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF\n";
Printf.printf "DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD\n";
Printf.printf "PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS),\n";
Printf.printf "EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF\n";
Printf.printf "SUCH DAMAGES.\n";
Printf.printf "\n";
Printf.printf "  17. Interpretation of Sections 15 and 16.\n";
Printf.printf "\n";
Printf.printf "  If the disclaimer of warranty and limitation of liability provided\n";
Printf.printf "above cannot be given local legal effect according to their terms,\n";
Printf.printf "reviewing courts shall apply local law that most closely approximates\n";
Printf.printf "an absolute waiver of all civil liability in connection with the\n";
Printf.printf "Program, unless a warranty or assumption of liability accompanies a\n";
Printf.printf "copy of the Program in return for a fee.\n";
Printf.printf "\n";
Printf.printf "                     END OF TERMS AND CONDITIONS\n";
Printf.printf "\n";
  | "how" ->
Printf.printf "            How to Apply These Terms to Your New Programs\n";
Printf.printf "\n";
Printf.printf "  If you develop a new program, and you want it to be of the greatest\n";
Printf.printf "possible use to the public, the best way to achieve this is to make it\n";
Printf.printf "free software which everyone can redistribute and change under these terms.\n";
Printf.printf "\n";
Printf.printf "  To do so, attach the following notices to the program.  It is safest\n";
Printf.printf "to attach them to the start of each source file to most effectively\n";
Printf.printf "state the exclusion of warranty; and each file should have at least\n";
Printf.printf "the \"copyright\" line and a pointer to where the full notice is found.\n";
Printf.printf "\n";
Printf.printf "    <one line to give the program's name and a brief idea of what it does.>\n";
Printf.printf "    Copyright (C) <year>  <name of author>\n";
Printf.printf "\n";
Printf.printf "    This program is free software: you can redistribute it and/or modify\n";
Printf.printf "    it under the terms of the GNU General Public License as published by\n";
Printf.printf "    the Free Software Foundation, either version 3 of the License, or\n";
Printf.printf "    (at your option) any later version.\n";
Printf.printf "\n";
Printf.printf "    This program is distributed in the hope that it will be useful,\n";
Printf.printf "    but WITHOUT ANY WARRANTY; without even the implied warranty of\n";
Printf.printf "    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n";
Printf.printf "    GNU General Public License for more details.\n";
Printf.printf "\n";
Printf.printf "    You should have received a copy of the GNU General Public License\n";
Printf.printf "    along with this program.  If not, see <http://www.gnu.org/licenses/>.\n";
Printf.printf "\n";
Printf.printf "Also add information on how to contact you by electronic and paper mail.\n";
Printf.printf "\n";
Printf.printf "  If the program does terminal interaction, make it output a short\n";
Printf.printf "notice like this when it starts in an interactive mode:\n";
Printf.printf "\n";
Printf.printf "    <program>  Copyright (C) <year>  <name of author>\n";
Printf.printf "    This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'.\n";
Printf.printf "    This is free software, and you are welcome to redistribute it\n";
Printf.printf "    under certain conditions; type `show c' for details.\n";
Printf.printf "\n";
Printf.printf "The hypothetical commands `show w' and `show c' should show the appropriate\n";
Printf.printf "parts of the General Public License.  Of course, your program's commands\n";
Printf.printf "might be different; for a GUI interface, you would use an \"about box\".\n";
Printf.printf "\n";
Printf.printf "  You should also get your employer (if you work as a programmer) or school,\n";
Printf.printf "if any, to sign a \"copyright disclaimer\" for the program, if necessary.\n";
Printf.printf "For more information on this, and how to apply and follow the GNU GPL, see\n";
Printf.printf "<http://www.gnu.org/licenses/>.\n";
Printf.printf "\n";
Printf.printf "  The GNU General Public License does not permit incorporating your program\n";
Printf.printf "into proprietary programs.  If your program is a subroutine library, you\n";
Printf.printf "may consider it more useful to permit linking proprietary applications with\n";
Printf.printf "the library.  If this is what you want to do, use the GNU Lesser General\n";
Printf.printf "Public License instead of this License.  But first, please read\n";
Printf.printf "<http://www.gnu.org/philosophy/why-not-lgpl.html>.\n";
Printf.printf "\n"
  | _ -> copyright()
